@TodoAPI_HostAddress = http://localhost:5241

GET {{TodoAPI_HostAddress}}/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImlzYXF1ZSIsInN1YiI6ImlzYXF1ZSIsImp0aSI6IjYwN2E0MTMwIiwicm9sZSI6ImFkbWluIiwiSWQiOiIxIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NDQ0MjUiLCJodHRwczovL2xvY2FsaG9zdDo0NDMzMyIsImh0dHA6Ly9sb2NhbGhvc3Q6NTI0MSIsImh0dHBzOi8vbG9jYWxob3N0OjcyOTkiXSwibmJmIjoxNzE2ODI0ODE3LCJleHAiOjE3MjQ3NzM2MTcsImlhdCI6MTcxNjgyNDgxOCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.GYyXsBVHIfDnCq2NGMkZ6GhAyxnrsdgRVjmt9VFSXdE

###

GET {{TodoAPI_HostAddress}}/items

###
GET {{TodoAPI_HostAddress}}/items/23

###
POST {{TodoAPI_HostAddress}}/items
Content-Type: application/json

{
  "Name": "dormir",
  "IsComplete": false,
  "TodoListId": 12
}

###
PUT {{TodoAPI_HostAddress}}/items/33
Content-Type: application/json

{
  "Name": "batata",
  "IsComplete": true,
  "TodoListId": 12
}

###
GET {{TodoAPI_HostAddress}}/lists

###
GET {{TodoAPI_HostAddress}}/lists/12

###
GET {{TodoAPI_HostAddress}}/lists/12/items

###
POST {{TodoAPI_HostAddress}}/lists
Content-Type: application/json

{
  "Name": "list 1",
  "Color": "000000",
  "TodoItems": []
}

###
DELETE {{TodoAPI_HostAddress}}/items

###
DELETE {{TodoAPI_HostAddress}}/items/1029

###
PUT {{TodoAPI_HostAddress}}/lists/12
Content-Type: application/json

{
  "Name": "list 20h41",
  "Color": "103421",
  "TodoItems": []
}

###
DELETE {{TodoAPI_HostAddress}}/lists

###
DELETE {{TodoAPI_HostAddress}}/lists/12/items

###
DELETE {{TodoAPI_HostAddress}}/lists/3



###
POST {{TodoAPI_HostAddress}}/users/login
Content-Type: application/json

{
  "Email": "isaque.dantas@gmail.com",
  "Password": "12345678"
}

###
POST {{TodoAPI_HostAddress}}/users
Content-Type: application/json

{
  "Name": "Isaque",
  "Username": "isaque-d",
  "Email": "itas@gmail.com",
  "Password": "12345678",
  "Role": "admin"
}

###
GET {{TodoAPI_HostAddress}}/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IklzYXF1ZSBWaWN0b3IgZG8gTmFzY2ltZW50byBEYW50YXMiLCJlbWFpbCI6ImlzYXF1ZS5kYW50YXNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwibmJmIjoxNzE2ODM4NzgwLCJleHAiOjE3MTY4NDU5ODAsImlhdCI6MTcxNjgzODc4MH0.gevrlLFL9LQTGOClDXY2iSb6jJOUwRnMpNwv7bZbJVU

###
GET {{TodoAPI_HostAddress}}/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IklzYXF1ZSIsImVtYWlsIjoiaXRhc0BnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJuYmYiOjE3MTY4Mzg2ODYsImV4cCI6MTcxNjg0NTg4NiwiaWF0IjoxNzE2ODM4Njg2fQ.AmU-KCaRUG_GUW_sXi3anOy9X6OfsYNG0FIGXgzOxtg
