@TodoAPI_HostAddress = http://localhost:5241

GET {{TodoAPI_HostAddress}}/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImlzYXF1ZSIsInN1YiI6ImlzYXF1ZSIsImp0aSI6IjYwN2E0MTMwIiwicm9sZSI6ImFkbWluIiwiSWQiOiIxIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NDQ0MjUiLCJodHRwczovL2xvY2FsaG9zdDo0NDMzMyIsImh0dHA6Ly9sb2NhbGhvc3Q6NTI0MSIsImh0dHBzOi8vbG9jYWxob3N0OjcyOTkiXSwibmJmIjoxNzE2ODI0ODE3LCJleHAiOjE3MjQ3NzM2MTcsImlhdCI6MTcxNjgyNDgxOCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.GYyXsBVHIfDnCq2NGMkZ6GhAyxnrsdgRVjmt9VFSXdE

###

GET {{TodoAPI_HostAddress}}/items

###
GET {{TodoAPI_HostAddress}}/items/23

###
POST {{TodoAPI_HostAddress}}/items
Content-Type: application/json

{
  "Name": "dormir",
  "IsComplete": false,
  "TodoListId": 12
}

###
PUT {{TodoAPI_HostAddress}}/items/33
Content-Type: application/json

{
  "Name": "batata",
  "IsComplete": true,
  "TodoListId": 12
}

###
GET {{TodoAPI_HostAddress}}/lists

###
GET {{TodoAPI_HostAddress}}/lists/12

###
GET {{TodoAPI_HostAddress}}/lists/12/items

###
POST {{TodoAPI_HostAddress}}/lists
Content-Type: application/json

{
  "Name": "list 1",
  "Color": "000000",
  "TodoItems": []
}

###
DELETE {{TodoAPI_HostAddress}}/items

###
DELETE {{TodoAPI_HostAddress}}/items/1029

###
PUT {{TodoAPI_HostAddress}}/lists/12
Content-Type: application/json

{
  "Name": "list 20h41",
  "Color": "103421",
  "TodoItems": []
}

###
DELETE {{TodoAPI_HostAddress}}/lists

###
DELETE {{TodoAPI_HostAddress}}/lists/12/items

###
DELETE {{TodoAPI_HostAddress}}/lists/3



###
POST {{TodoAPI_HostAddress}}/users/login
Content-Type: application/json

{
  "Email": "isaque@gmail.com",
  "Password": "12345"
}

###
POST {{TodoAPI_HostAddress}}/users
Content-Type: application/json

{
  "Name": "Isaque",
  "Username": "isaque-d",
  "Email": "itas@gmail.com",
  "Password": "12345678",
  "Role": "admin"
}

###
GET {{TodoAPI_HostAddress}}/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IklzYXF1ZSIsImVtYWlsIjoiaXNhcXVlQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTcxNjgzMjU1NiwiZXhwIjoxNzE2ODM5NzU2LCJpYXQiOjE3MTY4MzI1NTZ9.9bqtpoANOlBKHD9MOYA0vmCCuuLB3immJDZNwmB_lQ8
