@TodoAPI_HostAddress = http://localhost:5241

GET {{TodoAPI_HostAddress}}/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImlzYXF1ZSIsInN1YiI6ImlzYXF1ZSIsImp0aSI6IjM0ODNhYjRhIiwicm9sZSI6ImFkbWluIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NDQ0MjUiLCJodHRwczovL2xvY2FsaG9zdDo0NDMzMyIsImh0dHA6Ly9sb2NhbGhvc3Q6NTI0MSIsImh0dHBzOi8vbG9jYWxob3N0OjcyOTkiXSwibmJmIjoxNzE2ODIzNTMwLCJleHAiOjE3MjQ3NzIzMzAsImlhdCI6MTcxNjgyMzUzMSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.8YYQ6I135cA9ZJ9NMUWFCZq4USAke8ond21Ss7RM62U

###
GET {{TodoAPI_HostAddress}}/items/23

###
POST {{TodoAPI_HostAddress}}/items
Content-Type: application/json

{
  "Name": "dormir",
  "IsComplete": false,
  "TodoListId": 12
}

###
PUT {{TodoAPI_HostAddress}}/items/33
Content-Type: application/json

{
  "Name": "batata",
  "IsComplete": true,
  "TodoListId": 12
}

###
GET {{TodoAPI_HostAddress}}/lists

###
GET {{TodoAPI_HostAddress}}/lists/12

###
GET {{TodoAPI_HostAddress}}/lists/12/items

###
POST {{TodoAPI_HostAddress}}/lists
Content-Type: application/json

{
  "Name": "list 1",
  "Color": "000000",
  "TodoItems": []
}

###
DELETE {{TodoAPI_HostAddress}}/items

###
DELETE {{TodoAPI_HostAddress}}/items/1029

###
PUT {{TodoAPI_HostAddress}}/lists/12
Content-Type: application/json

{
  "Name": "list 20h41",
  "Color": "103421",
  "TodoItems": []
}

###
DELETE {{TodoAPI_HostAddress}}/lists

###
DELETE {{TodoAPI_HostAddress}}/lists/12/items

###
DELETE {{TodoAPI_HostAddress}}/lists/3